### ISSUE TITLE
Inbox

### ISSUE THREAD

**Issue by bijanbwb** [ElmOrlando/ElmGeolocation#1]
## TODO

- [x] Post to Meetup.com with information.
- [x] Convert to Create Elm App.
- [x] Fetch location with `elm-geolocation` package.
- [x] Render map with Google Maps API.
- [x] Subscribe to location updates.
- [x] Draw lines between location markers.

## NEXT IDEAS

- Based on real map data, plot points of items (maybe people or businesses) to collect/rescue/destroy.
- Draw spaceships over the map, each of which casts a "shadow".
- If the shadows of spaceships hover over the items, they are lost (and points are deducted).
- When the user's latitude and longitude matches the items, they are rescued (and points are added).
